### ISSUE TITLE
Sex chromosomes

### ISSUE THREAD

**Issue by marcabeer** [zgompert/spatpg#1]
Hi Dr. Gompert,

This is certainly a discussion item rather than an issue. The publication associated with spatpg indicates that the model motivating spatpg assumes diploid individuals. However, since the method takes as input allele counts, it is not clear whether it would perform well on sex chromosomes where ploidy varies with sex. In my case, individuals are of known sex, such that alleles can be counted accurately for the sex chromosomes. My sense is that I should be able to split my genomic dataset into autosomes and sex chromosomes so that Ne can be estimated separately for each split. Does this sound reasonable / am I missing something that would make results from running sex chromosomes in this way unreliable?

Cheers,
Marc Beer

**Comment by zgompert** [comment]
Hi Marc, your sense on this is spot on. The main issue would be that Ne (likely) differs for the sex chromosomes versus autosomes. As you note, this can be dealt with by analyzing autosomes and sex chromosomes separately such that Ne for each is estimated independently. As long as you do that, all should be well.

**Comment by marcabeer** [comment]
Thanks a bunch for the _very_ quick response. I'm excited to try out this method!

Cheers,
Marc
